baseURL = "https://sethmiller.me"
languageCode = "en-us"
disableHugoGeneratorInject = true

[params]
  title = "Seth Miller"
  description = "Seth Miller's blog."
  twitter = "tweetsethmiller"
  github = "iamseth"
keywords = ["test", "blah"]
