assetDir = "static"
languageCode = "en-us"
baseURL = "https://sethmiller.me"
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
pygmentsCodeFences = true
pygmentsUseClasses = true
